// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BitacoraAPI.Models;

public partial class Cuenta
{
    public int IdCuenta { get; set; }

    public int? IdUsuario { get; set; }

    public decimal? Tamanio { get; set; }

    public string Empresa { get; set; }

    public DateOnly? FechaCreacion { get; set; }

    public virtual Usuario IdUsuarioNavigation { get; set; }

    public virtual ICollection<Trade> Trades { get; set; } = new List<Trade>();
}