// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BitacoraAPI.Models;

public partial class TiposTrade
{
    public int IdTipoTrade { get; set; }

    public string TipoTrade { get; set; }

    public virtual ICollection<Trade> Trades { get; set; } = new List<Trade>();
}