// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BitacoraAPI.Models;

public partial class Trade
{
    public int IdTrade { get; set; }

    public int IdCuenta { get; set; }

    public int IdTipoTrade { get; set; }

    public DateTime FechaEntrada { get; set; }

    public DateTime? FechaSalida { get; set; }

    public string Divisa { get; set; }

    public decimal Riesgo { get; set; }

    public decimal Margin { get; set; }

    public decimal PrecioEntrada { get; set; }

    public decimal? PrecioSalida { get; set; }

    public decimal? TakeProfit { get; set; }

    public decimal? StopLoss { get; set; }

    public int? TradePips { get; set; }

    public decimal PorcentajePnl { get; set; }

    public decimal DineroPnl { get; set; }

    public string? Nota { get; set; }

    public virtual Cuenta IdCuentaNavigation { get; set; }

    public virtual TiposTrade IdTipoTradeNavigation { get; set; }
}